### ISSUE TITLE
Formatting Standards / Protobuf Library

### ISSUE THREAD

**Issue by bshaffer** [googleapis/proto-client-php#19]
There are quite a few formatting standards being skipped by these auto-generated files. Where does this need to be changed? Are we using [this one](https://github.com/protobuf-php/protobuf-plugin) or the DrSlump one?

I would suggest adding a link in the README or in `composer.json` in [`suggest`](https://getcomposer.org/doc/04-schema.md#suggest):

```json
{
    "suggest": {
        "protobuf-php/protobuf-php": "Used to generate the files in this repository"
    }
}
```

**Comment by michaelbausor** [comment]
We are using (a fork of) the DrSlump one: https://github.com/stanley-cheung/Protobuf-PHP
I will add the suggest line to `composer.json`

We will be switching to Google's implementation soon: https://github.com/google/protobuf/tree/master/php
So it is probably not worth trying to change the generator of these files, because they will replaced.
